### ISSUE TITLE
Behavior == null in TacticalModel callBeforeBehavior

### ISSUE THREAD

**Issue by jugdemon** [tumcms/MomenTUM#10]
After getting the basic scenario back to working, I tried to generate more complex geometry and I suddenly get a NullPointerException. I traced this down to line 217 where the pedestrian behavior returned is null and the attempt to use equals on it throws the exception. I am not clear, whether this could be resolved through reformulating the conditional, or whether there should be no null behavior here in the first place.

Attached you find a zip with the layout and ODMatrix and Simulation xml.

[momentum_data.zip](https://github.com/tumcms/MomenTUM/files/1540656/momentum_data.zip)

You have to adjust the file and output paths to make it work (or fail in the expected way in this case).

**Comment by PeterMKielar** [comment]
You send the complete momentum repository. Could you just send the configuration?

I can exchange your routing model with a Dijkstra model to test this.

Typically, the cause of these kinds of problems is an incorrect strategic model because
the behavior type is provided by the strategic model.

A cause of this error can be that the agent visits a goal location but then does not know what to do.

You could add an instant absorber to remove the agent the second it touches a destination location:
`<!-- deletes agents if he touches the destination location. -->`
`<absorber id="0" name="absorber" scenario="0" destination="1" type="DestinationInstantly"/>`

Or add an interaction time. The agent will stay in the area for this time duration
(if you use an DestinationSelectedAbsorber)
`<strategical id="0" name="odMatrx" type="ODMatrix" perceptualModel="0">`
`...`
`<property name="fulfilmentOverallDuration" type="Double" value="100.0"/> <!-- 100 seconds -->`
`...`
`</strategical>`
See: momentum-documentation\UserGuide\Explanations\BehaviorModelExamples\StrategicBehaviorModelExamples

fulfilmentOverallDuration is the duration an agent stays at all intermediate and destination locations.
If you desire different durations for staying in areas you can use the fulfilmentDuration complex Property.
You may also like to define the behavior types of the agents in the behavior type complex property of the od matrix. It will define what to do if the agents are close to the goal location.

**Comment by jugdemon** [comment]
This is weird, for me there are only 3 files in there. It is a folder named slightly different than the `momentum-data`. Note the difference between the dash and the underscore.

It is actually using Dijkstra. After having issues of scaling with my graph I approached the generation process differently. I took the basic scenario and scaled it up in size (ten-fold) and it worked. Then I added more obstacles to generate a more city-like environment for testing purposes. So this is still the basic example, but with larger and new geometry. I don't know how the bug arises. Please have a look yourself as it is either that my newly added walls and intermediates are somehow wrongly configured, or that there is a bug in your engine.

**Comment by PeterMKielar** [comment]
My bad, sorry.

You did a good job updating the OD-Matrix.CSV.
However, the rest of the OD matrix configuration needs to be updated too.
The behavior type has to be specified for each intermediate and destination area.
Thus:
`<complexProperty name="behaviorType" type="List" valueType="String">`
`<entry index="1" value="Queuing"/>`
`<entry index="2" value="Staying"/>`
`<entry index="3" value="Staying"/>`
`<entry index="4" value="Staying"/>`
`HERE, you miss 5, 6 and 7, index = area id`
`</complexProperty>`
You should use Staying for all types if you do not need queuing.
And define how long agents should stay here:
`<complexProperty name="fulfilmentDuration" type="List" valueType="Double">`
`<entry index="1" value="20.0"/>`
`<entry index="2" value="60.0"/>`
`Here, you miss your intermediate and destinations areas, index = area id`
`</complexProperty>`
You could use
`<property name="fulfilmentOverallDuration" type="Double" value="100.0"/> <!-- 100 seconds -->`
to define this for all areas at once (remove fulfilmentDuration).

Here you go:
![grafik](https://user-images.githubusercontent.com/30720746/33759148-8fe12dcc-dc01-11e7-8f6b-8134d2655cce.png)

And here the config. I removed density (which is super slow on these large simulations) and queuing, but added a more efficent graph generation algorithm:
![grafik](https://user-images.githubusercontent.com/30720746/33759280-11a0127e-dc02-11e7-8017-1a049a7ff23f.png)

Here is the zip:
[momentum-jg.zip](https://github.com/tumcms/MomenTUM/files/1542132/momentum-jg.zip)

Based on your task, you may need a better understanding of the queuing and staying models.

**Comment by jugdemon** [comment]
@PeterMKielar thank you very much for the detailed help. This is really saving me a lot of time! Is there a tutorial text written up on how to configure those elements. I tried to look through the examples folder but it was hard to find how exactly to configure these. With more intermediate nodes I will now be able to add them correctly.

Just a thought, if you catch a null-pointer there, you might want to throw an error message that mentions that those elements were not configured. I know it is a longshot to get out all those error messages, but it might reduce the overhead of getting into the framework for future users.

Regarding the OD Matrix, I wrote a quick R-script for a random OD Matrix. It assumes that there are as many destinations as origins and randomly connects destinations. The ratio of 1s in zeros in the sample vector defines the connectivity between nodes. The more zeros, the less dense the matrix is connect. It only needs a tad postprocessing as are is using hyphens for csv-entries.

```
numLoc <- 8
numOrigDest <- 2
dim.odm <- numLoc-numOrigDest
odm.r <- matrix(sample(c(0,0,1,1,1,1,1),dim.odm*dim.odm, replace=TRUE),dim.odm,dim.odm)
rownames(odm.r) <- 0:(dim.odm-1)
colnames(odm.r) <- numOrigDest:(dim.odm+numOrigDest-1)

set.seed(1913)
for(i in 1:dim.odm){
  num_edges <- sum(odm.r[i,])
  rand_nums <- runif(num_edges)
  rand_dist <- rand_nums/sum(rand_nums)
  odm.r[i,odm.r[i,]>0]<-rand_dist
}


write.csv2(odm.r,"odMatrix.csv")

as.data.frame(odm.r)
```

Maybe somebody can use this as well to quickly generate OD matrices for testing.

Thank you for the help, I really appreciate the responsiveness and help with using the framework!

**Comment by PeterMKielar** [comment]
@jugdemon You can push this R script to the documentation folder:
 momentum-documentation\UserGuide\Explanations\BehaviorModelExamples\StrategicBehaviorModelExamples
And add some comments in the file to descripe its purpose.

**Comment by jugdemon** [comment]
I created an annotated version, but I don't seem to have push rights to the repository. Can you edit my access rights? Or should I just post it here?

**Comment by PeterMKielar** [comment]
You have accept invitation to the team ☺

- - - - - - - - - - - - - - - -
Dr. rer. nat. Peter Kielar
Lehrstuhl für Computergestützte Modellierung und Simulation
Technische Universität München
Arcisstraße 21
D-80290 München

Tel: +49 89 289 23062
Fax: +49 89 289 25051
Mail: peter.kielar@tum.de
Web: www.cms.bgu.tum.de<http://www.cms.bgu.tum.de/>
GitHub: https://github.com/tumcms/MomenTUM
- - - - - - - - - - - - - - - -

Von: jugdemon [mailto:notifications@github.com]
Gesendet: Freitag, 8. Dezember 2017 15:11
An: tumcms/MomenTUM <MomenTUM@noreply.github.com>
Cc: Kielar, Peter <peter.kielar@tum.de>; Mention <mention@noreply.github.com>
Betreff: Re: [tumcms/MomenTUM] Behavior == null in TacticalModel callBeforeBehavior (#10)


I created an annotated version, but I don't seem to have push rights to the repository. Can you edit my access rights? Or should I just post it here?

**Comment by jugdemon** [comment]
I only opened the link apparently and forgot to actually click on accept. Now I uploaded it. My first commit.
