### ISSUE TITLE
Typo in IPedestrianExtansion

### ISSUE THREAD

**Issue by jugdemon** [tumcms/MomenTUM#2]
I am working through the routing algorithms in momentum for my Master Project and I noticed that one interface is called IPedestrianExt**a**nsion rather than IPedestrianExt**e**nsion.

**Comment by b-schwab** [comment]
Hi @jugdemon,

thanks for noticing and reporting!
I updated and renamed the relevant classes.
If you find more "Ext**e**nsions", please report again!

Best regards
Benedikt
