### ISSUE TITLE
Interface naming convention violated in IimmutablePath

### ISSUE THREAD

**Issue by jugdemon** [tumcms/MomenTUM#3]
I presume that in MomenTUM the usual convention of CamelCase is applied and that `IimmutablePath` appropriately should be called `IImmutablePath`. Alternatively, I personally would recommend to drop the `I` alltogether as it hinders readability and does not provide any novel or useful information. But that is up to your team to decide.

**Comment by PeterMKielar** [comment]
I changed the name. It will be online with my next push.
Regarding the I or Impl use in Java Code. I decided to use less noise: no Impl for implementation and I for interfaces. In general, I believe that it is helpful to know if I code against an interface or not.
