### ISSUE TITLE
Question about generating ODMatrix

### ISSUE THREAD

**Issue by jugdemon** [tumcms/MomenTUM#4]
I used the AutoCAD tool to generate the `layout.xml` and now I would like to generating the corresponding ODMatrix. Is there a tool available that I missed? Or do I need to generate the ODMatrix from the `<graph>` in the layout? I can write my own little program to do so, but it seems like a necessary step in most setups and so I was wondering, whether I can use an existing pipeline.

**Comment by PeterMKielar** [comment]
Hi jugdemon

At the moment we do not provide a tool to automatically generate an OD Matrix.
But you can use excel or a text editor to define a matrix.
Furthermore, the OD Matrix is graph independent.

Explanations:
The OD Matrix is given as csv file into the simulator.

E.g.: \momentum-documentation\UserGuide\startHere\BasicExample\basicExampleODMatrix.csv
;1;2;3;4
0;0.1;0.3;0.6;0.0
1;0.0;0.0;0.5;0.5
2;0.0;0.0;0.5;0.5
5;0.1;0.3;0.0;0.6
Here the first item (column 0, row 0) is always empty.
The first row defines the destinations (or intermediate goal) ids and the first column defines the origin (or intermediate goal) ids. You can find the ids of the areas in your layout.

E.g.: momentum-documentation\UserGuide\startHere\BasicExample\basicExampleLayout.xml
<area id="4" name="DestinationY" type="Destination">
<point x="28" y="21" />
<point x="30" y="21" />
<point x="30" y="21.5" />
<point x="28" y="21.5" />
 <point x="28" y="21" />
</area>
Here 4 is the id can use in the first row of the OD csv file.

Another example:
;1;2 <- empty;destination/intermediate id=1; destination/intermediate id2 … 
0; 0.3;0.7 <- origin/intermediate id=0; probability to go to destination/intermediate of the column
1;0.5;0.5  <- origin/intermediate id=1; probability to go to destination/intermediate of the column
Thus, an agent starting at origin 1 will select (here) intermediate 1 (50%) or destination 2 (50%)
The graph will automatically find the areas and include them in the graph.

You need <graphOperation id="X" name="seeds" type="VertexCreateSeedBased"/> to create vertices at the centers of the areas. Using the graph model of the examples is mostly sufficient to create useful navigation graphs that include vertices in areas.

Regards
Peter

**Comment by jugdemon** [comment]
@PeterMKielar thank you for the explanation. I was currently generating my graphs within autocad and I had assumed that for intermediate zones it would be enough to have a vertex within the zone, does it need to be the center?

**Comment by PeterMKielar** [comment]
Hi jugdemon
Please review the class
momentum-model\src\main\java\tum\cms\sim\momentum\model\layout\graph\raw\FromConfigurationOperation.java
I updated the code so that you can use:
`<graphOperation id="0" name="fromConfig" type="FromConfiguration" order="0">`
`<property name="graphId" type="Integer" value="0"/>`
**`<property name="insideAreaSeed" type="Boolean" value="True"/>`**
`</graphOperation>`
See also:
momentum-documentation\UserGuide\Explanations\LayoutExamples\Graph\ GraphFromConfiguration.xml
The new tag insideAreaSeed will change the behavior of the “FromConfiguration” operation. It will find the first vertex inside an area and assigns it to the area.

I don’t have the time for testing this feature. Thus, please check if it works as desired.

Regards
Peter

**Comment by jugdemon** [comment]
@PeterMKielar thank you for the quick fix. I will use it and give a quick feedback here if all works as desired.

**Comment by jugdemon** [comment]
@PeterMKielar I tested it and it only works after a small adjustment. It assumes that there is only one vertice in each area. If there is more than one, it fails to retrieve the area associated with the second vertex due to your `HashSet`.

I replaced the get-operation to obtain `area` in the stream with `.orElse(null)` and I do a second check whether no object has been found and fall back on the else-clause of the `isSeed`-if-clause.

Below the full `isSeed`-if-clause:

```
if(isSeed) {
	Area area = this.scenarioManager.getAreas()
			.stream()
			.filter(existingArea -> {

				if(!alreadySeedAreas.contains(existingArea)) {
					
					if(precisionSeed != null && FastMath.abs(existingArea.getPointOfInterest().distance(center)) < precisionSeed) {
						 
						 return true;
					}
					else if (insideAreaSeed != null && insideAreaSeed && existingArea.getGeometry().contains(center)) {
						 
						 return true;
					}
				}
				return false;
			})
			.findFirst().orElse(null);
	
	if(area!=null) {
		alreadySeedAreas.add(area);
		
		// select one that was not taken already
		// put into graph factory
		
		newVertex = GraphTheoryFactory.createVertex(area.getGeometry(), vertexConfiguration.getId());
	} else {
		newVertex = GraphTheoryFactory.createVertexCyleBased(center, vertexConfiguration.getId());
	}
}
else {
	newVertex = GraphTheoryFactory.createVertexCyleBased(center, vertexConfiguration.getId());
}
```

This seems to fix it for me. I am still having other issues (see new issues), so I cannot guarantee that all issues are resolved

**Comment by PeterMKielar** [comment]
@jugdemon 
I used your changes and validated them with unit tests. Well done.
