### ISSUE TITLE
Visualisation Zoom issue makes drawning panel empty

### ISSUE THREAD

**Issue by jugdemon** [tumcms/MomenTUM#7]
I now produced the first version of a dump cognitive model (i.e. a plain old copy of Dijkstra). The simulation completes and when I load the data into the Visualisation that works as well. However, as the graph is large, I can only see a small fraction of it. Trying to zoom just clears the drawing panel and does not redraw the graph at a different size.

Attached you find the simulation in question:

edit: 
[output.zip](https://github.com/tumcms/MomenTUM/files/1518807/output.zip)

**Comment by jugdemon** [comment]
note that zooming back to 1 restores the graphics.

**Comment by PeterMKielar** [comment]
Uncheck (right-hand-side) the graph checkbox to hide the graph (and the lattice).
It is known that large graphs and layouts reduce performance.
